### ISSUE TITLE
Contact Info Required

### ISSUE THREAD

**Issue by kalraritz** [Logesh-Github/ImageSlider#1]
Hi Logesh,

I am Ritesh. I believe that you were working on Clubhop App. Do you have sometime to talk about it?

If yes, can you please drop an email with your contact information at kalraritz@hotmail.com

Thanks
Ritesh

**Comment by Logesh-Github** [comment]
I'll be sharing it soon.

**Comment by kalraritz** [comment]
Thanks for your reply.
